config/routes.rb
Rails.application.routes.draw do

  root 'hotels#index'

  resources :hotels do
    resources :comments
  end
  resources :streets
  resources :cities
  resources :countries

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :streets
  belongs_to :country, optional: true

  before_save :normalize_city_name

  validates :name, presence: true

  private
    def normalize_city_name
      self.name = name.downcase.titleize
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :hotel, optional: true
  belongs_to :user, optional: true

  validates :rating, presence: true, inclusion: {in: 1..5}
  validates :content, presence: true, length: { maximum: 500, message: 'Comment shouldnt be longer than 500 characters' }
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities

  before_save :normalize_country_name

  validates :name, presence: true

  private
    def normalize_country_name
      self.name = name.downcase.titleize
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :comments
  belongs_to :street, optional: true

  before_save :normalize_title

  validates :title, presence: true, uniqueness: {message: 'Hotel already exists!'}
  validates :room, presence: true
  validates :price, presence: true, numericality: {message: 'must be written in numeric value'}
  validates :breakfast, inclusion: {in: ['yes', 'no'], message: 'please write only YES/NO'}, presence: true

  mount_uploader :image, ImageUploader

  private
    def normalize_title
      self.title = title.downcase.titleize
  end

end

app/models/street.rb
class Street < ApplicationRecord
  has_many :hotels
  belongs_to :city, optional: true

  accepts_nested_attributes_for :hotels, :city

  before_save :normalize_street_name

  validates :name , presence: true

  private
    def normalize_street_name
      self.name = name.downcase.titleize
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments

  validates :login, presence: true, uniqueness: true, length: { maximum: 20, message: 'Must be shorter than 20 characters' }
  validates :password, presence: true, length: { minimum: 5 , message: 'Must be longer than 5 characters' }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_hotel

  def create
    @comment = @hotel.comments.create(comment_params)
    redirect_to hotel_path(@hotel)
  end

  def destroy
    @comment = @hotel.comments.find(params[:id])
    @comment.destroy
    redirect_to hotel_path(@hotel)
  end

  private
    def comment_params
      params.require(:comment).permit(:rating, :content)
    end

    def find_hotel
      @hotel = Hotel.find(params[:hotel_id])
    end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

  before_action :find_hotel, only: [:edit, :show, :update, :destroy]

  def index
    @hotels = Hotel.all
  end

  def create
    @hotel = Hotel.new(hotel_params)

    if @hotel.save
      redirect_to @hotel
    else
      render 'new'
    end
  end

  def new
    @hotel = Hotel.new
#    @street = @hotel.street.build
  end

  def edit
  end

  def show
  end

  def update
    if @hotel.update(hotel_params)
      redirect_to @hotel
    else
      redirect_to 'edit'
    end
  end

  def destroy
    @hotel.destroy

    redirect_to hotels_path
  end

  private
    def find_hotel
      @hotel = Hotel.find(params[:id])
    end

    def hotel_params
      params.require(:hotel).permit(:title, :breakfast, :room, :image, :image_cache, :price, street_params: [:name])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_comment_form.html.haml
- @hotel.comments.each do |comment|
  %li
    Rating:
    =comment.rating
  %li
    Comment:
    =comment.content

app/views/hotels/_hotel_form.html.haml
= label :hotel, :title, 'Title'
= text_field :hotel, :title

= label :hotel, :breakfast, 'Breakfast'
= text_field :hotel, :breakfast

= label :hotel, :room, 'Room Description'
= text_field :hotel, :room

= label :hotel, :price, 'Price (USD)'
= text_field :hotel, :price

= label :hotel, :street, 'Street'
= text_field :street, :name

= label :hotel, :city, 'City'
= text_field :city, :name

= label :hotel, :country, 'Country'
= text_field :country, :name

= label :hotel, :image, 'Add an Image'
= file_field :hotel, :image
= hidden_field :hotel, :image_cache

app/views/hotels/edit.html.haml
%h2 Edit #{@hotel.title}

= form_for :hotel, url: hotel_path(@hotel), :method => :put do

  - if @hotel.errors.any?
    #error_explanation
      %h2
      %ul
      - @hotel.errors.full_messages.each do |msg|
        %li= msg

  = render 'hotel_form'

  = submit_tag 'Save Hotel'
  = link_to 'Back', hotels_path

app/views/hotels/index.html.haml
%h2 Hotels

%table#hotels
  %thead
    %tr
      %th Title
      %th Price
  %tbody
    - @hotels.each do |hotel|
      %tr
        %td= hotel.title
        %td= hotel.price
        %td= link_to 'More about', hotel_path(hotel)
        %td= link_to 'Edit', edit_hotel_path(hotel)
= link_to 'Add new hotel', new_hotel_path

app/views/hotels/new.html.haml
%h1 Create new hotel

= form_for :hotels, url: hotels_path, :method  => :post do

  - if @hotel.errors.any?
    #error_explanation
      %h2
      %ul
      - @hotel.errors.full_messages.each do |msg|
        %li= msg

  = render 'hotel_form'

  = submit_tag 'Save Hotel'
  = link_to 'Back', hotels_path

app/views/hotels/show.html.haml
%h1 Details about

%ul#details
  %li
    Breakfast included?:
    =@hotel.breakfast
  %li
    Image of the hotel:
    =@hotel.image
%h2 Room description:
%p#description= @hotel.room

=link_to 'Back', hotels_path
=link_to 'Delete', hotel_path(@hotel), method: :delete

%h3 Add a comment:
= form_with( model: [ @hotel, @hotel.comments.build], local:true) do
  %p
  = label :rating, 'Rating'
  = text_field :comment, :rating

  = label :content, 'Comment'
  = text_field :comment, :content

  = submit_tag 'Post Comment'

%h4 Comments
- @hotel.comments.each do |comment|
  %li
    Rating:
    =comment.rating
  %li
    Comment:
    =comment.content

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Advisor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>